<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content 
            CopyToOutputDirectory="Always"
            Include="Images\Icons\ForPacks\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControls" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\Backgrounds\" />
    <Folder Include="Images\Icons\Buttons\" />
    <Folder Include="View\Pages\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Icons\ForPacks\DefaultIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="View\MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
